# Generated by Django 2.2.5 on 2020-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user-placeholder.jpg', upload_to='profile-images/'),
        ),
    ]
