# Generated by Django 2.2.5 on 2020-05-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('language_biography', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('situation', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipantRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Role')),
                ('session_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.SessionParticipant')),
            ],
            options={
                'unique_together': {('session_participant', 'role')},
            },
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='roles',
            field=models.ManyToManyField(through='metadata.SessionParticipantRole', to='metadata.Role'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Session'),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quality', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low'), ('U', 'n/a')], default='U', max_length=20)),
                ('child_speech', models.CharField(choices=[('L', 'little'), ('LN', 'little to none'), ('M', 'medium'), ('H', 'much'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('directedness', models.CharField(choices=[('AA', 'adult>adult'), ('AC', 'adult>child'), ('CC', 'child>child'), ('M', 'mixed'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('dene_speech', models.CharField(choices=[('L', 'little'), ('M', 'medium'), ('H', 'much'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Session')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'audio'), ('V', 'video')], max_length=5)),
                ('format', models.CharField(choices=[('mov', 'MOV'), ('mp4', 'MP4'), ('mts', 'MTS'), ('wav', 'WAV')], max_length=3)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Recording')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'participant')},
        ),
        migrations.CreateModel(
            name='ParticipantLangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('first', models.BooleanField()),
                ('second', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Language')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Participant')),
            ],
            options={
                'unique_together': {('participant', 'language')},
            },
        ),
    ]
