# Generated by Django 3.0.7 on 2020-12-31 17:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactivity', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('interactive', 'Interactive'), ('non-interactive', 'Non Interactive'), ('semi-interactive', 'Semi Interactive')], default='Unspecified', max_length=20)),
                ('planning_type', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('spontaneous', 'Spontaneous'), ('semi-spontaneous', 'Semi Spontaneous'), ('planned', 'Planned')], default='Unspecified', max_length=20)),
                ('involvement', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('elicited', 'Elicited'), ('non-elicited', 'Non Elicited'), ('no-observer', 'No Observer')], default='Unspecified', max_length=20)),
                ('social_context', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('Family', 'Familiy'), ('Private', 'Private'), ('Public', 'Public'), ('Controlled environment', 'Controlled Environment'), ('Public (school)', 'Public School'), ('Community', 'Community')], default='Unspecified', max_length=30)),
                ('event_structure', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('Monologue', 'Monologue'), ('Dialogue', 'Dialogue'), ('Multilogue', 'Multilogue'), ('Not a natural format', 'Not A Natural Format'), ('Conversation', 'Conversation')], default='Unspecified', max_length=30)),
                ('channel', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('Face to Face', 'Face To Face'), ('Experimental setting', 'Experimental Setting'), ('Broadcasting', 'Broadcasting'), ('Telephone', 'Telephone'), ('wizard-of-oz', 'Wizard Of Oz'), ('Human-machine dialogue', 'Human Machine Dialogue'), ('Other', 'Other')], default='Unspecified', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='None', max_length=50)),
                ('subgenre', models.CharField(blank=True, max_length=50, null=True)),
                ('task', models.CharField(blank=True, max_length=50, null=True)),
                ('modalities', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('communication_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.CommunicationContext')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Oceania', 'Oceania'), ('North-America', 'North America'), ('Middle-America', 'Middle America'), ('South-America', 'South America')], default='Unspecified', max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('anonymized', models.CharField(max_length=3, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_day', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True)),
                ('birth_month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('birth_year', models.IntegerField(blank=True, choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049), (2050, 2050), (2051, 2051), (2052, 2052), (2053, 2053), (2054, 2054), (2055, 2055), (2056, 2056), (2057, 2057), (2058, 2058), (2059, 2059), (2060, 2060), (2061, 2061), (2062, 2062), (2063, 2063), (2064, 2064), (2065, 2065), (2066, 2066), (2067, 2067), (2068, 2068), (2069, 2069), (2070, 2070), (2071, 2071), (2072, 2072), (2073, 2073), (2074, 2074), (2075, 2075), (2076, 2076), (2077, 2077), (2078, 2078), (2079, 2079), (2080, 2080), (2081, 2081), (2082, 2082), (2083, 2083), (2084, 2084), (2085, 2085), (2086, 2086), (2087, 2087), (2088, 2088), (2089, 2089), (2090, 2090), (2091, 2091), (2092, 2092), (2093, 2093), (2094, 2094), (2095, 2095), (2096, 2096), (2097, 2097), (2098, 2098), (2099, 2099)], null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('language_biography', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('situation', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipantRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.Role')),
                ('session_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.SessionParticipant')),
            ],
            options={
                'unique_together': {('session_participant', 'role')},
            },
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='roles',
            field=models.ManyToManyField(through='metadata.SessionParticipantRole', to='metadata.Role'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Session'),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quality', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low'), ('U', 'n/a')], default='U', max_length=20)),
                ('child_speech', models.CharField(choices=[('L', 'little'), ('LN', 'little to none'), ('M', 'medium'), ('H', 'much'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('directedness', models.CharField(choices=[('AA', 'adult>adult'), ('AC', 'adult>child'), ('CC', 'child>child'), ('M', 'mixed'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('dene_speech', models.CharField(choices=[('L', 'little'), ('M', 'medium'), ('H', 'much'), ('N', 'none'), ('U', 'n/a')], default='U', max_length=30)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('pid', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('audio', 'audio'), ('video', 'video')], max_length=5)),
                ('format', models.CharField(choices=[('mov', 'mov'), ('mp4', 'mp4'), ('mts', 'mts'), ('wav', 'wav')], max_length=3)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Recording')),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Content')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Location')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'participant')},
        ),
        migrations.CreateModel(
            name='ParticipantLangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('first', models.BooleanField()),
                ('second', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.Language')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Participant')),
            ],
            options={
                'unique_together': {('participant', 'language')},
            },
        ),
    ]
