# Generated by Django 3.1.4 on 2021-01-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(blank=True, default='User license required', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='corpus',
            name='access',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.access'),
        ),
    ]
