# Generated by Django 2.2.5 on 2020-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('mov', 'mov'), ('mp4', 'mp4'), ('mts', 'mts'), ('wav', 'wav')], max_length=3),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video')], max_length=5),
        ),
    ]
