# Generated by Django 3.0.7 on 2020-07-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20200621_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionparticipantrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.Role'),
        ),
    ]
