# Generated by Django 2.2.5 on 2020-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20200306_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.AlterField(
            model_name='session',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='situation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
