# Generated by Django 3.1.4 on 2021-01-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20210124_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.access'),
        ),
    ]
