# Generated by Django 2.2.5 on 2020-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20200307_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='bytes',
            new_name='size',
        ),
    ]
