# Generated by Django 2.2.5 on 2020-04-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20200410_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('researcher', 'researcher'), ('unknown', 'unknown'), ('great grandfather', 'great grandfather'), ('grandmother', 'grandmother'), ('linguist', 'linguist'), ('mother', 'mother'), ('sister', 'sister'), ('greatuncle', 'greatuncle'), ('grandfather', 'grandfather'), ('playmate', 'playmate'), ('greataunt', 'greataunt'), ('classmate', 'classmate'), ('aunt', 'aunt'), ('older brother', 'older brother'), ('older sister', 'older sister'), ('uncle', 'uncle'), ('child', 'child'), ('relative', 'relative'), ('family friend', 'family friend'), ('stepfather', 'stepfather'), ('brother', 'brother'), ('cousin', 'cousin'), ('great grandmother', 'great grandmother'), ('recorder', 'recorder'), ('nephew', 'nephew'), ('teacher', 'teacher'), ('father', 'father'), ('greatgrandmother', 'greatgrandmother'), ('niece', 'niece')], max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Session')),
            ],
        ),
    ]
