# Generated by Django 3.0.7 on 2020-07-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20200710_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlanginfo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.Language'),
        ),
    ]
