# Generated by Django 3.1.4 on 2021-01-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20210124_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='length',
        ),
        migrations.AddField(
            model_name='participant',
            name='ethnic_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
