# Generated by Django 2.2.5 on 2020-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20200411_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionparticipant',
            name='role',
            field=models.CharField(choices=[('niece', 'niece'), ('nephew', 'nephew'), ('older brother', 'older brother'), ('greatgrandmother', 'greatgrandmother'), ('classmate', 'classmate'), ('family friend', 'family friend'), ('grandmother', 'grandmother'), ('linguist', 'linguist'), ('stepfather', 'stepfather'), ('aunt', 'aunt'), ('unknown', 'unknown'), ('older sister', 'older sister'), ('researcher', 'researcher'), ('uncle', 'uncle'), ('father', 'father'), ('mother', 'mother'), ('recorder', 'recorder'), ('relative', 'relative'), ('grandfather', 'grandfather'), ('great grandfather', 'great grandfather'), ('greatuncle', 'greatuncle'), ('child', 'child'), ('teacher', 'teacher'), ('greataunt', 'greataunt'), ('sister', 'sister'), ('playmate', 'playmate'), ('cousin', 'cousin'), ('great grandmother', 'great grandmother'), ('brother', 'brother')], max_length=20),
        ),
    ]
