# Generated by Django 3.1.4 on 2021-01-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20210124_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='link',
            field=models.URLField(default='https//:unknown_link.ch'),
        ),
    ]
