# Generated by Django 3.1.4 on 2021-02-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_corpus_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='dene_speech',
            new_name='language_speech',
        ),
    ]
