# Generated by Django 3.0.7 on 2020-07-23 18:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
