# Generated by Django 2.2.5 on 2020-04-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20200411_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionparticipant',
            name='role',
            field=models.CharField(choices=[('greatuncle', 'greatuncle'), ('older sister', 'older sister'), ('niece', 'niece'), ('great grandfather', 'great grandfather'), ('grandmother', 'grandmother'), ('recorder', 'recorder'), ('brother', 'brother'), ('greataunt', 'greataunt'), ('unknown', 'unknown'), ('stepfather', 'stepfather'), ('researcher', 'researcher'), ('family friend', 'family friend'), ('child', 'child'), ('sister', 'sister'), ('teacher', 'teacher'), ('mother', 'mother'), ('greatgrandmother', 'greatgrandmother'), ('relative', 'relative'), ('cousin', 'cousin'), ('aunt', 'aunt'), ('older brother', 'older brother'), ('nephew', 'nephew'), ('uncle', 'uncle'), ('classmate', 'classmate'), ('great grandmother', 'great grandmother'), ('father', 'father'), ('playmate', 'playmate'), ('linguist', 'linguist'), ('grandfather', 'grandfather')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'participant')},
        ),
    ]
