# Generated by Django 2.2.5 on 2020-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20200412_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionparticipant',
            name='role',
            field=models.CharField(choices=[('greatuncle', 'greatuncle'), ('great grandmother', 'great grandmother'), ('aunt', 'aunt'), ('family friend', 'family friend'), ('brother', 'brother'), ('niece', 'niece'), ('greatgrandmother', 'greatgrandmother'), ('uncle', 'uncle'), ('father', 'father'), ('linguist', 'linguist'), ('researcher', 'researcher'), ('classmate', 'classmate'), ('teacher', 'teacher'), ('cousin', 'cousin'), ('mother', 'mother'), ('grandmother', 'grandmother'), ('stepfather', 'stepfather'), ('relative', 'relative'), ('grandfather', 'grandfather'), ('greataunt', 'greataunt'), ('nephew', 'nephew'), ('recorder', 'recorder'), ('sister', 'sister'), ('older sister', 'older sister'), ('unknown', 'unknown'), ('child', 'child'), ('great grandfather', 'great grandfather'), ('playmate', 'playmate'), ('older brother', 'older brother')], max_length=20),
        ),
    ]
