# Generated by Django 3.0.7 on 2020-07-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20200725_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='communication_context',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.CommunicationContext'),
        ),
    ]
