# Generated by Django 3.1.4 on 2021-02-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20210216_1501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('recording', 'format')},
        ),
    ]
