# Generated by Django 3.0.7 on 2020-07-25 19:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20200725_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('Unknown', 'Unknown'), ('Unspecified', 'Unspecified'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Oceania', 'Oceania'), ('North-America', 'North America'), ('Middle-America', 'Middle America'), ('South-America', 'South America')], default='Unspecified', max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='country',
        ),
        migrations.AddField(
            model_name='corpus',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Location'),
        ),
    ]
