# Generated by Django 2.2.5 on 2020-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20200412_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='languages',
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='role',
            field=models.CharField(choices=[('aunt', 'aunt'), ('brother', 'brother'), ('child', 'child'), ('classmate', 'classmate'), ('cousin', 'cousin'), ('family friend', 'family friend'), ('father', 'father'), ('grandfather', 'grandfather'), ('grandmother', 'grandmother'), ('great grandfather', 'great grandfather'), ('great grandmother', 'great grandmother'), ('greataunt', 'greataunt'), ('greatgrandmother', 'greatgrandmother'), ('greatuncle', 'greatuncle'), ('linguist', 'linguist'), ('mother', 'mother'), ('nephew', 'nephew'), ('niece', 'niece'), ('older brother', 'older brother'), ('older sister', 'older sister'), ('playmate', 'playmate'), ('recorder', 'recorder'), ('relative', 'relative'), ('researcher', 'researcher'), ('sister', 'sister'), ('stepfather', 'stepfather'), ('teacher', 'teacher'), ('uncle', 'uncle'), ('unknown', 'unknown')], max_length=20),
        ),
    ]
