# Generated by Django 2.2.5 on 2020-04-13 06:16

from django.db import migrations


def add_languages(apps, _):
    languages = [
        ('Dene', 'chp'),
        ('English', 'eng'),
        ('German', 'deu'),
    ]

    Language = apps.get_model('metadata', 'Language')

    for name, iso in languages:
        Language.objects.update_or_create(iso_code=iso, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20200413_0611'),
    ]

    operations = [
        migrations.RunPython(add_languages),
    ]

