# Generated by Django 3.0.7 on 2020-07-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20200725_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Location'),
        ),
    ]
