# Generated by Django 2.2.5 on 2020-04-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20200413_0616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantlanginfo',
            unique_together={('participant', 'language')},
        ),
    ]
