# Generated by Django 3.0.7 on 2020-07-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20200725_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Contact'),
        ),
    ]
