# Generated by Django 3.0.7 on 2020-07-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_auto_20200725_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='communication_context',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.CommunicationContext')),
            ],
        ),
        migrations.AddField(
            model_name='corpus',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.Content'),
        ),
    ]
