# Generated by Django 2.2.5 on 2020-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_auto_20200427_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
