# Generated by Django 3.0.7 on 2020-07-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_auto_20200729_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.Content'),
        ),
    ]
