# Generated by Django 3.0.7 on 2020-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_auto_20200729_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='content',
            name='modalities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subgenre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='task',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
