# Generated by Django 2.2.5 on 2019-09-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('segmentation', 'segmentation'), ('transcription', 'transcription/translation'), ('glossing', 'glossing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT-STARTED', 'not started'), ('BARRED', 'barred'), ('DEFERRED', 'defer'), ('RESERVED', 'reserved for'), ('IN PROGRESS', 'in progress'), ('CHECKED', 'CHECK'), ('INCOMPLETE', 'incomplete'), ('COMPLETE', 'complete'), ('NO MEDIA', 'no media'), ('PROBLEMS', 'problems'), ('UNCLEAR', 'UNCLEAR')], default='NOT-STARTED', max_length=30),
        ),
    ]
