# Generated by Django 2.2.5 on 2020-03-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_comment_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('education', models.CharField(max_length=100)),
                ('language_biography', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('situation', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('participants', models.ManyToManyField(to='workflow.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantLangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('first', models.BooleanField()),
                ('second', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Language')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='languages',
            field=models.ManyToManyField(through='workflow.ParticipantLangInfo', to='workflow.Language'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'audio'), ('V', 'video')], max_length=5)),
                ('format', models.CharField(choices=[('mov', 'MOV'), ('mp4', 'MP4'), ('mts', 'MTS'), ('wav', 'WAV')], max_length=3)),
                ('duration', models.DurationField()),
                ('bytes', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Recording')),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Session'),
        ),
    ]
